version: '3.12'

services:
  app:
    build: .
    ports:
      - "5000:5000"  
                     
    volumes:
      - .:/app       
                     
    env_file:
      - .env        
    environment:
      - FLASK_ENV=development 
      - OTHER_VARIABLE=value
