version: '3.12'

services:
  app:
    build: .
    ports:
      - "5000:5000"  
                     
    volumes:
      - .:/app       
      - model_cache:/root/.cache  # Cache for downloaded models
                     
    env_file:
      - .env        
    environment:
      - FLASK_ENV=development 
      - OTHER_VARIABLE=value
      - STRIPE_SUCCESS_URL=https://prepzo-client-git-dev-prepzo.vercel.app/dashboard
      - STRIPE_CANCEL_URL=https://prepzo-client-git-dev-prepzo.vercel.app

volumes:
  model_cache:
